# Generated by Django 4.1.7 on 2023-03-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_user_admin_remove_user_id_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('suburb', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('postal', models.IntegerField()),
                ('parking_allign', models.CharField(max_length=30)),
                ('parking_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('ev', models.BooleanField()),
                ('handicap', models.BooleanField()),
                ('price_weekday', models.FloatField(max_length=5)),
                ('price_weekend', models.FloatField(max_length=5)),
                ('status', models.CharField(max_length=20)),
                ('deleted', models.BooleanField()),
                ('providerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
    ]
