# Generated by Django 4.1.7 on 2023-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_property_id_alter_property_providerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ev',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='handicap',
            field=models.CharField(max_length=3),
        ),
    ]
