# Generated by Django 4.1.7 on 2023-03-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_property_ev_alter_property_handicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
