# Generated by Django 4.1.7 on 2023-03-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
