# Generated by Django 4.1.7 on 2023-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_requestmodel_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='booking_cost',
            field=models.FloatField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
