# Generated by Django 4.1.7 on 2023-04-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_requestmodel_booking_cost'),
        ('members', '0012_remove_user_is_admin_remove_user_last_login_and_more'),
    ]

    operations = [
    ]
